services:

  transactions-service:
    image: gradle:8.7-jdk21
    container_name: transactions-service
    working_dir: /home/gradle
    volumes:
      - ./src:/home/gradle/src
      - ./build.gradle:/home/gradle/build.gradle
      - ./build:/home/gradle/build  # Mount the build directory for reports
      - gradle_cache:/home/gradle/.gradle # Cache Gradle dependencies
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/transactionsDB
      - JDBC_DATABASE_USERNAME=dbuser
      - JDBC_DATABASE_PASSWORD=dbpassword
    depends_on:
      - db

  db:
    image: postgres:17.0
    container_name: transactions-service-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=transactionsDB

volumes:
  gradle_cache:
